/*Enconding=UTF-8*/
/* Generated by Together */

package netgest.bo.parser.symbol;

public class IfExpression implements ExpressionSymbol {
    public ExpressionSymbol getExpression(){ return expression; }

    public void setExpression(ExpressionSymbol expression){ this.expression = expression; }

    public ExpressionSymbol getThenExpression(){ return thenExpression; }

    public void setThenExpression(ExpressionSymbol thenExpression){ this.thenExpression = thenExpression; }

    public ExpressionSymbol getElseExpression(){ return elseExpression; }

    public void setElseExpression(ExpressionSymbol elseExpression){ this.elseExpression = elseExpression; }

    public String toJAVA(){
        StringBuffer sb = new StringBuffer();
        sb.append("(").append(expression.toJAVA()).append(" ? ");
        sb.append(thenExpression.toJAVA()).append(" : ");
        sb.append(elseExpression.toJAVA()).append(")");
        return sb.toString();
    }
    private ExpressionSymbol expression;
    private ExpressionSymbol thenExpression;
    private ExpressionSymbol elseExpression;
}
