package netgest.bo.impl.document.merge.gestemp.client;
/**
 * Generated by the Oracle JDeveloper 10g Web Services Interface Generator
 * Date Created: Wed May 16 17:24:19 BST 2007
 * 
 * This interface lists the subset of public methods that you
 * selected for inclusion in your web service's public interface.
 * It is referenced in the web.xml deployment descriptor for this service.
 * 
 * This file should not be edited.
 */

public interface IWSDocument 
{
    public byte[] getDocumentByBoui(long boui);

    public void setDocumentByBoui(long boui, byte[] buff);

    public byte[] getDocument(String sessionID, String transactionID, long boui);

    public void setDocument(String sessionID, String transactionID, long boui, byte[] buff);

    public void setPrinted(String sessionID, String transactionID, long parent, long boui);

    public String getAllTemplates();

    public long createDocument(String fileName, byte[] buff);

    public long createDocumentInSession(String sessionID, String fileName, byte[] buff);

    public void removeDocument(String sessionID, long boui);
}
