package netgest.bo.message.server.sms;
/**
 * Generated by the Oracle JDeveloper 10g Web Services Stub/Skeleton Generator.
 * Date Created: Fri Feb 09 09:03:19 GMT 2007
 * 
 * <pre>
 * &lt;xsd:complexType name="AuthInfoWS" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 * &lt;xsd:sequence>
 * &lt;xsd:element name="application" nillable="true" type="xsd:string"/>
 * &lt;xsd:element name="login" nillable="true" type="xsd:string"/>
 * &lt;xsd:element name="password" nillable="true" type="xsd:string"/>
 * &lt;/xsd:sequence>
 * &lt;/xsd:complexType>
 * </pre>
 */

public class AuthInfoWS 
{
    private String m_application;

    private String m_login;

    private String m_password;

    public AuthInfoWS()
    {
    }

    public AuthInfoWS(String application, String login, String password)
    {
        m_application = application;
        m_login = login;
        m_password = password;
    }

    public void setApplication(String application)
    {
        m_application = application;
    }

    public String getApplication()
    {
        return m_application;
    }

    public void setLogin(String login)
    {
        m_login = login;
    }

    public String getLogin()
    {
        return m_login;
    }

    public void setPassword(String password)
    {
        m_password = password;
    }

    public String getPassword()
    {
        return m_password;
    }
}