package netgest.bo.message.server.sms;
/**
 * Generated by the Oracle JDeveloper 10g Web Services Stub/Skeleton Generator.
 * Date Created: Fri Feb 09 09:03:24 GMT 2007
 * 
 * <pre>
 * &lt;xsd:complexType name="Status" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 * &lt;xsd:sequence>
 * &lt;xsd:element name="id" nillable="true" type="xsd:string"/>
 * &lt;xsd:element name="status" type="xsd:int"/>
 * &lt;xsd:element name="message" nillable="true" type="xsd:string"/>
 * &lt;/xsd:sequence>
 * &lt;/xsd:complexType>
 * </pre>
 */

public class Status 
{
    private String m_id;

    private Integer m_status;

    private String m_message;

    public Status()
    {
    }

    public Status(String id, Integer status, String message)
    {
        m_id = id;
        m_status = status;
        m_message = message;
    }

    public void setId(String id)
    {
        m_id = id;
    }

    public String getId()
    {
        return m_id;
    }

    public void setStatus(Integer status)
    {
        m_status = status;
    }

    public Integer getStatus()
    {
        return m_status;
    }

    public void setMessage(String message)
    {
        m_message = message;
    }

    public String getMessage()
    {
        return m_message;
    }
}