package netgest.bo.message.server.sms;
/**
 * Generated by the Oracle JDeveloper 10g Web Services Stub/Skeleton Generator.
 * Date Created: Fri Feb 09 09:03:22 GMT 2007
 * 
 * <pre>
 * &lt;xsd:complexType name="Submission" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 * &lt;xsd:sequence>
 * &lt;xsd:element name="message" nillable="true" type="xsd:string"/>
 * &lt;xsd:element name="contactLists" nillable="true" type="ns10:ArrayOfstring"/>
 * &lt;xsd:element name="recipients" nillable="true" type="ns10:ArrayOfstring"/>
 * &lt;xsd:element name="sender" nillable="true" type="xsd:string"/>
 * &lt;xsd:element name="validity" type="xsd:int"/>
 * &lt;xsd:element name="notification" type="xsd:boolean"/>
 * &lt;xsd:element name="deliveryDate" type="xsd:dateTime"/>
 * &lt;/xsd:sequence>
 * &lt;/xsd:complexType>
 * </pre>
 */

public class Submission 
{
    private String m_message;

    private String[] m_contactLists;

    private String[] m_recipients;

    private String m_sender;

    private Integer m_validity;

    private Boolean m_notification;

    private java.util.Date m_deliveryDate;

    public Submission()
    {
    }

    public Submission(String message, String[] contactLists, String[] recipients, String sender, Integer validity, Boolean notification, java.util.Date deliveryDate)
    {
        m_message = message;
        m_contactLists = contactLists;
        m_recipients = recipients;
        m_sender = sender;
        m_validity = validity;
        m_notification = notification;
        m_deliveryDate = deliveryDate;
    }

    public void setMessage(String message)
    {
        m_message = message;
    }

    public String getMessage()
    {
        return m_message;
    }

    public void setContactLists(String[] contactLists)
    {
        m_contactLists = contactLists;
    }

    public String[] getContactLists()
    {
        return m_contactLists;
    }

    public void setRecipients(String[] recipients)
    {
        m_recipients = recipients;
    }

    public String[] getRecipients()
    {
        return m_recipients;
    }

    public void setSender(String sender)
    {
        m_sender = sender;
    }

    public String getSender()
    {
        return m_sender;
    }

    public void setValidity(Integer validity)
    {
        m_validity = validity;
    }

    public Integer getValidity()
    {
        return m_validity;
    }

    public void setNotification(Boolean notification)
    {
        m_notification = notification;
    }

    public Boolean getNotification()
    {
        return m_notification;
    }

    public void setDeliveryDate(java.util.Date deliveryDate)
    {
        m_deliveryDate = deliveryDate;
    }

    public java.util.Date getDeliveryDate()
    {
        return m_deliveryDate;
    }
}