package netgest.bo.message.server.sms;
import org.apache.soap.transport.http.SOAPHTTPConnection;
//import oracle.soap.transport.http.OracleSOAPHTTPConnection;
import org.apache.soap.encoding.SOAPMappingRegistry;
import java.net.URL;
import org.apache.soap.rpc.Call;
import org.apache.soap.Constants;
import java.util.Vector;
import org.apache.soap.rpc.Parameter;
import org.apache.soap.rpc.Response;
import org.apache.soap.Fault;
import org.apache.soap.SOAPException;
import org.apache.soap.encoding.soapenc.BeanSerializer;
import org.apache.soap.util.xml.QName;
import java.util.Properties;
/**
 * Generated by the Oracle JDeveloper 10g Web Services Stub/Skeleton Generator.
 * Date Created: Fri Feb 09 09:03:25 GMT 2007
 * WSDL URL: file:/C:/Documents and Settings/jcarreira/Desktop/lixo/SubmissionManager.wsdl
 * 
 * Services Info
 */

public class SubmissionManagerStub 
{
    public SubmissionManagerStub()
    {
        m_httpConnection = new SOAPHTTPConnection();
        m_smr = new SOAPMappingRegistry();

        BeanSerializer beanSer = new BeanSerializer();
        m_smr.mapTypes(Constants.NS_URI_SOAP_ENC, new QName("http://www.themindelectric.com/package/com.mobicomp.mmh.sms.webservice.server/", "AuthInfoWS"), AuthInfoWS.class, beanSer, beanSer);
        m_smr.mapTypes(Constants.NS_URI_SOAP_ENC, new QName("http://www.themindelectric.com/package/com.mobicomp.smsexpress.webservice.server.submission/", "Submission"), Submission.class, beanSer, beanSer);
        m_smr.mapTypes(Constants.NS_URI_SOAP_ENC, new QName("http://www.themindelectric.com/package/com.mobicomp.smsexpress.webservice.server.submission/", "Status"), Status.class, beanSer, beanSer);
    }

    private String _endpoint = "https://smsexpress.tmn.pt/smsexpress-webservices/glue/SubmissionManager";

    public String getEndpoint()
    {
        return _endpoint;
    }

    public void setEndpoint(String endpoint)
    {
        _endpoint = endpoint;
    }

    private SOAPHTTPConnection m_httpConnection = null;
    private SOAPMappingRegistry m_smr = null;

    public Status sendMultiSms(AuthInfoWS auth, Submission multiSms) throws Exception
    {
        Status returnVal = null;

        URL endpointURL = new URL(_endpoint);
        Call call = new Call();
        call.setSOAPTransport(m_httpConnection);
        call.setTargetObjectURI("http://www.mobicomp.com/smsexpress");
        call.setMethodName("sendMultiSms");
        call.setEncodingStyleURI(Constants.NS_URI_SOAP_ENC);

        Vector params = new Vector();
        params.addElement(new Parameter("auth", AuthInfoWS.class, auth, null));
        params.addElement(new Parameter("multiSms", Submission.class, multiSms, null));
        call.setParams(params);

        call.setSOAPMappingRegistry(m_smr);

        Response response = call.invoke(endpointURL, "sendMultiSms");

        if (!response.generatedFault())
        {
            Parameter result = response.getReturnValue();
            returnVal = (Status)result.getValue();
        }
        else
        {
            Fault fault = response.getFault();
            throw new SOAPException(fault.getFaultCode(), fault.getFaultString());
        }

        return returnVal;
    }

    public void setMaintainSession(boolean maintainSession)
    {
        m_httpConnection.setMaintainSession(maintainSession);
    }

    public boolean getMaintainSession()
    {
        return m_httpConnection.getMaintainSession();
    }
}